// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWywVSz1wTEpWrVwUAlWpXuyniAXCN9E',
    appId: '1:1080574811821:web:6db69567172752f9527024',
    messagingSenderId: '1080574811821',
    projectId: 'tanaka-6eb29',
    authDomain: 'tanaka-6eb29.firebaseapp.com',
    storageBucket: 'tanaka-6eb29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPW7PkhAfFO0akFgJjP-aD5Tmj6Fqih0',
    appId: '1:1080574811821:android:02762151deea9f94527024',
    messagingSenderId: '1080574811821',
    projectId: 'tanaka-6eb29',
    storageBucket: 'tanaka-6eb29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXj3YRy8sRaHEeTD8bJ89HE4soGfUfTM',
    appId: '1:1080574811821:ios:989531a12046e295527024',
    messagingSenderId: '1080574811821',
    projectId: 'tanaka-6eb29',
    storageBucket: 'tanaka-6eb29.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXj3YRy8sRaHEeTD8bJ89HE4soGfUfTM',
    appId: '1:1080574811821:ios:989531a12046e295527024',
    messagingSenderId: '1080574811821',
    projectId: 'tanaka-6eb29',
    storageBucket: 'tanaka-6eb29.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkWywVSz1wTEpWrVwUAlWpXuyniAXCN9E',
    appId: '1:1080574811821:web:1618e36fe42e5dbe527024',
    messagingSenderId: '1080574811821',
    projectId: 'tanaka-6eb29',
    authDomain: 'tanaka-6eb29.firebaseapp.com',
    storageBucket: 'tanaka-6eb29.firebasestorage.app',
  );

}